# provenance: Human/Claude-authored platform code (engineered, not agent-generated)
"""Deliverable-contract validation for benchmark workspaces.

Every L2/L3 task promises the same machine-checkable contract so any
harness's output is scored identically:

  * the expected artifacts exist,
  * ``report.json`` parses and carries the required metric keys,
  * ``predict.py`` honors the CLI (``--input params.json --output pred.npz``)
    and returns psi shaped (N, 96, 64) on the frozen evaluation grid,
  * (L3 only) no workspace Python file imports ``autotokamak`` — the
    from-scratch condition is audited, not merely requested.

``score_against_frozen`` computes the head-to-head relative-L2 numbers on a
frozen test set generated by ``bench freeze-testset``.
"""
from __future__ import annotations

import json
import os
import re
import signal
import subprocess
import sys
import tempfile
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np

from autotokamak.bench.taskspec import TaskSpec

# Frozen evaluation grid (matches benchmarks/assets/eval_grid.json and the
# task text): psi is (nZ, nR) = (96, 64).
DEFAULT_GRID = {
    "R": {"n": 64, "low": 0.15, "high": 0.80},
    "Z": {"n": 96, "low": -0.40, "high": 0.40},
}
GRID_ATOL = 1e-9
REQUIRED_REPORT_KEYS = ("n_solves_attempted", "n_solves_succeeded", "metrics")
REQUIRED_METRIC_BLOCKS = ("test_rel_l2", "baseline_rel_l2")
REQUIRED_METRIC_STATS = ("mean", "median", "p90")


@dataclass
class ContractReport:
    """One gate per check; ``passed`` is the AND of all hard gates."""

    gates: dict[str, bool] = field(default_factory=dict)
    notes: dict[str, str] = field(default_factory=dict)

    @property
    def passed(self) -> bool:
        return bool(self.gates) and all(self.gates.values())

    def set(self, gate: str, ok: bool, note: str = "") -> None:
        self.gates[gate] = bool(ok)
        if note:
            self.notes[gate] = note

    def to_dict(self) -> dict[str, Any]:
        return {"passed": self.passed, "gates": self.gates, "notes": self.notes}


def load_grid(grid_json: Optional[Path] = None) -> dict:
    if grid_json is not None and Path(grid_json).is_file():
        return json.loads(Path(grid_json).read_text())
    return DEFAULT_GRID


def grid_axes(grid: dict) -> tuple[np.ndarray, np.ndarray]:
    r = grid["R"]
    z = grid["Z"]
    return (
        np.linspace(float(r["low"]), float(r["high"]), int(r["n"])),
        np.linspace(float(z["low"]), float(z["high"]), int(z["n"])),
    )


def audit_no_autotokamak_import(workspace: Path) -> list[str]:
    """Return every workspace .py file that references autotokamak (L3 gate)."""
    pattern = re.compile(
        r"^\s*(?:import|from)\s+autotokamak\b"                 # plain import
        r"|import_module\(\s*[\"']autotokamak"                 # importlib
        r"|__import__\(\s*[\"']autotokamak",                   # dunder
        re.MULTILINE,
    )
    offenders: list[str] = []
    for p in sorted(Path(workspace).rglob("*.py")):
        if p.is_symlink() or any(part == "__pycache__" for part in p.parts):
            continue
        try:
            if pattern.search(p.read_text(encoding="utf-8", errors="replace")):
                offenders.append(str(p.relative_to(workspace)))
        except OSError:
            continue
    return offenders


def _check_report_json(report_path: Path, report: ContractReport) -> None:
    try:
        data = json.loads(report_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        report.set("report_parses", False, f"{type(exc).__name__}: {exc}")
        return
    report.set("report_parses", True)

    missing = [k for k in REQUIRED_REPORT_KEYS if k not in data]
    metrics = data.get("metrics") or {}
    for block in REQUIRED_METRIC_BLOCKS:
        stats = metrics.get(block) or {}
        missing += [
            f"metrics.{block}.{s}" for s in REQUIRED_METRIC_STATS if s not in stats
        ]
    report.set(
        "report_keys", not missing,
        f"missing: {missing}" if missing else "",
    )


def run_predict(
    workspace: Path,
    params: list[dict],
    *,
    timeout_seconds: int = 600,
    python: str = sys.executable,
) -> dict[str, np.ndarray]:
    """Invoke workspace ``predict.py`` per contract; return the npz arrays."""
    # Resolve so the temp params/pred paths stay valid under cwd=workspace
    # even when the caller passed a repo-relative workspace path.
    workspace = Path(workspace).resolve()
    # Scoring subprocess: no provider credentials (predict.py must be
    # offline), own process group so a timeout kills solver children too —
    # the task text tells agents to run solves in child processes.
    env = {k: v for k, v in os.environ.items()
           if not re.search(r"API_KEY|SECRET|TOKEN", k)}
    with tempfile.TemporaryDirectory(dir=workspace) as td:
        inp = Path(td) / "params.json"
        out = Path(td) / "pred.npz"
        inp.write_text(json.dumps(params), encoding="utf-8")
        proc = subprocess.Popen(
            [python, "predict.py", "--input", str(inp), "--output", str(out)],
            cwd=workspace,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            env=env,
            start_new_session=True,
        )
        try:
            _, stderr = proc.communicate(timeout=timeout_seconds)
        except subprocess.TimeoutExpired:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            proc.communicate()
            raise RuntimeError(
                f"predict.py timed out after {timeout_seconds}s (process group killed)"
            ) from None
        if proc.returncode != 0:
            raise RuntimeError(
                f"predict.py exit {proc.returncode}\nstderr:\n{stderr[-2000:]}"
            )
        with np.load(out) as npz:
            return {k: np.array(npz[k]) for k in npz.files}


def _check_predict(workspace: Path, grid: dict, report: ContractReport,
                   timeout_seconds: int) -> None:
    probe = [
        {"r0": 0.45, "a": 0.15, "kappa": 1.3, "delta": 0.2, "Ip": 140e3},
        {"r0": 0.40, "a": 0.12, "kappa": 1.1, "delta": 0.1, "Ip": 100e3},
        {"r0": 0.50, "a": 0.18, "kappa": 1.5, "delta": 0.3, "Ip": 180e3},
    ]
    try:
        arrays = run_predict(workspace, probe, timeout_seconds=timeout_seconds)
    except Exception as exc:  # noqa: BLE001
        report.set("predict_runs", False, f"{type(exc).__name__}: {exc}")
        return
    report.set("predict_runs", True)

    R_ref, Z_ref = grid_axes(grid)
    psi = arrays.get("psi")
    ok_shape = psi is not None and psi.shape == (len(probe), len(Z_ref), len(R_ref))
    report.set(
        "predict_shape", ok_shape,
        "" if ok_shape else f"psi shape {None if psi is None else psi.shape} "
        f"!= {(len(probe), len(Z_ref), len(R_ref))}",
    )
    R, Z = arrays.get("R"), arrays.get("Z")
    ok_grid = (
        R is not None and Z is not None
        and R.shape == R_ref.shape and Z.shape == Z_ref.shape
        and np.allclose(R, R_ref, atol=GRID_ATOL)
        and np.allclose(Z, Z_ref, atol=GRID_ATOL)
    )
    report.set("predict_grid", ok_grid, "" if ok_grid else "R/Z axes differ from the frozen grid")


def validate_deliverables(
    workspace: Path,
    task: TaskSpec,
    *,
    grid_json: Optional[Path] = None,
    run_predict_check: bool = True,
    predict_timeout: int = 600,
) -> ContractReport:
    workspace = Path(workspace)
    report = ContractReport()

    for rel in task.expected_artifacts:
        p = workspace / rel
        report.set(f"artifact:{rel}", p.is_file() and p.stat().st_size > 0)

    if "report.json" in task.expected_artifacts and (workspace / "report.json").is_file():
        _check_report_json(workspace / "report.json", report)

    if task.access_level == "L3":
        offenders = audit_no_autotokamak_import(workspace)
        report.set(
            "no_autotokamak_import", not offenders,
            f"offenders: {offenders}" if offenders else "",
        )

    if run_predict_check and (workspace / "predict.py").is_file():
        _check_predict(workspace, load_grid(grid_json), report, predict_timeout)

    return report


def rel_l2_errors(psi_pred: np.ndarray, psi_true: np.ndarray) -> np.ndarray:
    """Per-sample relative L2 over the finite ground-truth grid points.

    A NaN *prediction* at a finite ground-truth point is a full-magnitude
    miss (pred treated as 0), never a free pass — ``nan_to_num`` on the
    diff would score an all-NaN prediction as perfect. (Scoring change
    2026-08-18; earlier scores differ by <=1.4e-4 on matrix-v2.)
    """
    if len(psi_pred) != len(psi_true):
        raise ValueError(
            f"sample count mismatch: {len(psi_pred)} predictions "
            f"vs {len(psi_true)} ground-truth maps"
        )
    errs = []
    for pred, true in zip(psi_pred, psi_true):
        mask = np.isfinite(true)
        denom = np.linalg.norm(true[mask])
        num = np.linalg.norm(np.nan_to_num(pred[mask]) - true[mask])
        errs.append(num / denom if denom > 0 else np.inf)
    return np.array(errs)


def nan_at_finite_fraction(psi_pred: np.ndarray, psi_true: np.ndarray) -> float:
    """Fraction of finite-ground-truth points where the prediction is NaN."""
    total = hits = 0
    for pred, true in zip(psi_pred, psi_true):
        mask = np.isfinite(true)
        total += int(mask.sum())
        hits += int(np.sum(~np.isfinite(pred[mask])))
    return hits / total if total else 0.0


def full_grid_rel_l2_errors(psi_pred: np.ndarray, psi_true: np.ndarray) -> np.ndarray:
    """Relative L2 that ALSO charges for predicted field outside the plasma.

    The contract metric (:func:`rel_l2_errors`) masks to finite ground truth,
    so a prediction that fills the vacuum region is scored as if it had not.
    That is not hypothetical: one run reported 0.1142 on the interior while
    emitting a near-full-magnitude spurious plasma outside the boundary; its
    honest score is 1.94, four times WORSE than the mean-map baseline.

    Ground truth outside the last closed flux surface is "no plasma", so the
    correct target there is zero contribution and any predicted magnitude is
    error. The denominator stays the interior norm of truth, so the two
    metrics are directly comparable and their RATIO is the size of the
    exterior violation in physical terms.

    This is recorded ALONGSIDE the contract metric, never in place of it —
    archived scores stay comparable.
    """
    if len(psi_pred) != len(psi_true):
        raise ValueError(
            f"sample count mismatch: {len(psi_pred)} predictions "
            f"vs {len(psi_true)} ground-truth maps"
        )
    errs = []
    for pred, true in zip(psi_pred, psi_true):
        interior = np.isfinite(true)
        exterior = ~interior
        denom = np.linalg.norm(true[interior])
        if denom <= 0:
            errs.append(np.inf)
            continue
        sq = np.linalg.norm(np.nan_to_num(pred[interior]) - true[interior]) ** 2
        # A finite prediction where there is no plasma is spurious field.
        sq += np.linalg.norm(np.nan_to_num(pred[exterior])) ** 2
        errs.append(np.sqrt(sq) / denom)
    return np.array(errs)


def prediction_shape_stats(psi_pred: np.ndarray, psi_true: np.ndarray) -> dict[str, float]:
    """Structural checks on a prediction that relative-L2 alone cannot see.

    Two failure modes in the existing corpus motivate these, and neither
    trips a contract gate:

    * ``nan_mask_agreement`` — matrix-v2's L3-ursa passed 9/9 gates at
      rel-L2 0.96 because ``predict.py`` wrote **zeros** where the plasma
      boundary ends instead of NaN. The field was structurally wrong in a
      way a scalar error norm reports only as "large".
    * ``pred_pixel_std_mean`` — a predictor that ignores its inputs and
      emits one constant map still produces finite, correctly shaped
      output. Near-zero spread across test samples is the signature.
      Reported next to the ground truth's own spread so it is a ratio the
      reader can judge, not a bare number.
    """
    agree = total = 0
    for pred, true in zip(psi_pred, psi_true):
        agree += int(np.sum(np.isnan(pred) == np.isnan(true)))
        total += int(true.size)
    # Pixels outside every test plasma are NaN in all samples, so nanmean /
    # nanstd over them is an expected empty slice, not a defect.
    with np.errstate(invalid="ignore"), warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        pred_std = float(np.nanmean(np.nanstd(psi_pred, axis=0)))
        true_std = float(np.nanmean(np.nanstd(psi_true, axis=0)))
    return {
        "nan_mask_agreement": round(agree / total, 6) if total else 0.0,
        "pred_nan_fraction": round(float(np.mean(np.isnan(psi_pred))), 6),
        "truth_nan_fraction": round(float(np.mean(np.isnan(psi_true))), 6),
        "pred_pixel_std_mean": pred_std if np.isfinite(pred_std) else None,
        "truth_pixel_std_mean": true_std if np.isfinite(true_std) else None,
        "pred_over_truth_spread": (round(pred_std / true_std, 6)
                                   if np.isfinite(pred_std) and np.isfinite(true_std)
                                   and true_std > 0 else None),
    }


def baseline_rel_l2(psi_true: np.ndarray) -> dict[str, Any]:
    """Relative L2 of the trivial mean-psi-map predictor on the SAME set.

    This is the yardstick every accuracy figure is quoted against, and it
    was previously recomputed on each ``tools/matrix_report.py`` render and
    never stored. Persisting it with the score makes a result.json
    self-contained.
    """
    with np.errstate(invalid="ignore"), warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)  # all-NaN columns
        mean_map = np.nanmean(psi_true, axis=0)
    errs = rel_l2_errors(np.repeat(mean_map[None, ...], len(psi_true), axis=0), psi_true)
    finite = errs[np.isfinite(errs)]
    if not finite.size:
        return {"mean": None, "median": None, "p90": None}
    return {
        "mean": float(np.mean(finite)),
        "median": float(np.median(finite)),
        "p90": float(np.percentile(finite, 90)),
    }


def score_against_frozen(
    workspace: Path,
    test_set_h5: Path,
    *,
    predict_timeout: int = 3600,
) -> dict[str, Any]:
    """Head-to-head relative-L2 vs the frozen test set (bench freeze-testset)."""
    from autotokamak.data.h5io import read_h5_arrays
    from autotokamak.surrogate.dataset import PARAM_ORDER

    arrays_h5 = read_h5_arrays(test_set_h5)
    ok = np.asarray(arrays_h5.success, dtype=bool)
    psi_true = arrays_h5.psi[ok]
    records = [
        {p: float(arrays_h5.inputs[p][i]) for p in PARAM_ORDER}
        for i in np.flatnonzero(ok)
    ]
    arrays = run_predict(Path(workspace), records, timeout_seconds=predict_timeout)
    psi_pred = arrays["psi"]
    expected = (len(records),) + tuple(psi_true.shape[1:])
    if tuple(psi_pred.shape) != expected:
        raise RuntimeError(
            f"predict.py returned psi shaped {tuple(psi_pred.shape)}, "
            f"expected {expected} — refusing to score a misaligned subset"
        )
    errs = rel_l2_errors(psi_pred, psi_true)
    finite = errs[np.isfinite(errs)]
    base = baseline_rel_l2(psi_true)
    test_mean = float(np.mean(finite)) if finite.size else None
    # Accuracy against the mean-psi-map baseline, the figure the matrix
    # report has always plotted; stored here so it survives without a
    # re-render. Same definition: 100 * (1 - rel_l2 / baseline_rel_l2).
    accuracy_pct = (round(100.0 * (1.0 - test_mean / base["mean"]), 4)
                    if test_mean is not None and base["mean"] else None)
    # Full-grid variant: same denominator, but spurious exterior field is
    # charged for. The inflation ratio IS the mask-failure measure, and
    # unlike a pixel-count it scales with how wrong the field actually is.
    full = full_grid_rel_l2_errors(psi_pred, psi_true)
    full_finite = full[np.isfinite(full)]
    full_mean = float(np.mean(full_finite)) if full_finite.size else None
    inflation = (round(full_mean / test_mean, 4)
                 if full_mean is not None and test_mean else None)
    return {
        "n_test": int(len(errs)),
        "n_scored": int(len(finite)),
        "pred_nan_at_finite": round(nan_at_finite_fraction(psi_pred, psi_true), 6),
        "test_rel_l2_full_grid": {
            "mean": full_mean,
            "median": float(np.median(full_finite)) if full_finite.size else None,
            "p90": float(np.percentile(full_finite, 90)) if full_finite.size else None,
        },
        # >1 means the prediction puts field where there is vacuum. ~1.0 is
        # clean; ~1.2 is a NaN-convention slip; ~17 is a fabricated plasma.
        "exterior_inflation": inflation,
        "test_rel_l2": {
            "mean": test_mean,
            "median": float(np.median(finite)) if finite.size else None,
            "p90": float(np.percentile(finite, 90)) if finite.size else None,
        },
        "baseline_rel_l2": base,
        "accuracy_pct": accuracy_pct,
        **prediction_shape_stats(psi_pred, psi_true),
    }
