#!/usr/bin/env python3
# provenance: Human/Claude-authored platform code (engineered, not agent-generated)
"""Emit the paper's appendix tables straight from the frozen artifacts.

The appendix reproduces the task text and the solution-shape cross comparison.
Retyping either is how an appendix quietly stops matching the thing it
documents, so both are generated:

    python tools/render_paper_tables.py --tag matrix-v4-20260919 \
           --out docs/paper/neurips_benchmark/tables

  task_text_L3.tex   the verbatim L3 problem statement
  task_diff.tex      every hunk by which the L2 text differs from it
  solution_shape.tex the 12-dimension cross comparison, one column per cell
"""
from __future__ import annotations

import argparse
import csv
import difflib
import re
from pathlib import Path

import yaml

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from autotokamak.bench import glossary  # noqa: E402

CELLS = ["L2-cursor", "L2-dspy", "L2-pi", "L2-ursa",
         "L3-cursor", "L3-dspy", "L3-pi", "L3-ursa"]


def esc(text: str) -> str:
    """LaTeX-escape a value that may contain underscores and plus signs."""
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("&", r"\&"),
                 ("%", r"\%"), ("#", r"\#"), ("$", r"\$")):
        text = text.replace(a, b)
    return text


def esc_prose(text: str) -> str:
    """Escape a definition sentence, keeping its punctuation readable."""
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("&", r"\&"),
                 ("%", r"\%"), ("#", r"\#"), ("$", r"\$"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        text = text.replace(a, b)
    return " ".join(text.split())


def task_text(l3: Path, out: Path) -> None:
    problem = yaml.safe_load(l3.read_text())["problem"].rstrip()
    out.write_text(
        "% generated by tools/render_paper_tables.py -- do not edit\n"
        "{\\scriptsize\n\\begin{verbatim}\n" + problem + "\n\\end{verbatim}\n}\n")


def task_diff(l2: Path, l3: Path, out: Path) -> None:
    a = yaml.safe_load(l2.read_text())["problem"].splitlines()
    b = yaml.safe_load(l3.read_text())["problem"].splitlines()
    diff = list(difflib.unified_diff(a, b, fromfile="L2_mini_v3",
                                     tofile="L3_mini_v3", lineterm="", n=0))
    n_hunks = sum(1 for line in diff if line.startswith("@@"))
    out.write_text(
        "% generated by tools/render_paper_tables.py -- do not edit\n"
        f"% {n_hunks} hunks\n"
        "{\\scriptsize\n\\begin{verbatim}\n" + "\n".join(diff)
        + "\n\\end{verbatim}\n}\n")


ABBREV = {"L2-cursor": "2c", "L2-dspy": "2d", "L2-pi": "2p", "L2-ursa": "2u",
          "L3-cursor": "3c", "L3-dspy": "3d", "L3-pi": "3p", "L3-ursa": "3u"}


def solution_shape(tag_dir: Path, out: Path) -> None:
    """One row per (dimension, distinct modal value), naming the cells.

    The natural layout -- dimension by cell -- is far too wide once the values
    are spelled out, and abbreviating the values is exactly what the glossary
    exists to avoid. Grouping by value carries the same information in a
    readable width and makes agreement visible at a glance.
    """
    with (tag_dir / "solution_shape.csv").open() as fh:
        rows = list(csv.DictReader(fh))
    lines = ["% generated by tools/render_paper_tables.py -- do not edit",
             "\\begin{tabular}{@{}ll>{\\raggedright\\arraybackslash}p{0.44\\textwidth}@{}}", "\\toprule",
             "\\textbf{Dimension} & \\textbf{Cells} & \\textbf{Modal value} \\\\",
             "\\midrule"]
    for row in rows:
        groups: dict[str, list[str]] = {}
        for c in CELLS:
            v = (row[c] or "-").split(" (")[0]
            groups.setdefault(v, []).append(ABBREV[c])
        first = True
        for v, cells in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            label = esc(row["dimension"]) if first else ""
            shown = "---" if v == "-" else "\\code{" + esc(v) + "}"
            lines.append(f"{label} & {', '.join(cells)} & {shown} \\\\")
            first = False
        lines.append("\\addlinespace[2pt]")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))


# Terms the paper prints outside the solution-shape table.
EXTRA_TERMS = [
    "uncertainty", "uncertainty_ensemble", "uncertainty_gp", "residual_ucb",
    "space_filling", "random", "feasibility", "gradient_sensitivity",
    "lhs", "sobol", "uniform_random", "mc_dropout", "deep_ensemble",
    "kernel_ridge", "mlp_torch", "val_threshold_70pct", "round_cap",
    "stop_threshold_met", "stop_without_threshold", "stop_unexplained",
    "agree", "partial", "mismatch", "unverifiable_from_code",
    "model_informed", "criterion_switched", "evidence_grounded",
    "chain_agreement", "adaptive_in_name_only", "prose_only", "top_k",
]


def glossary_tex(tag_dir: Path, out: Path) -> None:
    """Define every canonical token the paper prints, and nothing else.

    A code a reader has to guess at is not a measurement, and a glossary of
    tokens the paper never uses is padding. So the token list is read back off
    the generated tables.
    """
    tokens: set[str] = set()
    with (tag_dir / "solution_shape.csv").open() as fh:
        for row in csv.DictReader(fh):
            for c in CELLS:
                value = (row[c] or "").split(" (")[0]
                tokens.update(glossary.split_value(value))
    tokens.discard("-")
    # Counted shapes ("11_modules", "7_runnable_scripts") differ only in their
    # number; one generic entry each, not one per observed count.
    tokens = {t for t in tokens
              if not re.match(r"^\d+_(modules|runnable_scripts)$", t)}
    tokens.update(EXTRA_TERMS)
    generic = [
        ("N\\_modules", "The pipeline is spread over N source files, none of "
         "them dominant; contrast \\code{single\\_script}."),
        ("N\\_runnable\\_scripts", "N files are runnable as programs. More than "
         "one means the documented single command is really a sequence."),
    ]

    lines = ["% generated by tools/render_paper_tables.py -- do not edit",
             "\\begin{description}[leftmargin=1.2em,style=nextline,font=\\ttfamily\\small]"]
    entries = [(esc(t), esc_prose(glossary.define(t)))
               for t in sorted(tokens) if glossary.define(t)]
    for token, definition in sorted(entries + generic):
        lines.append("\\item[" + token + "] " + definition)
    lines += ["\\end{description}", ""]
    out.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tag", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    root = Path(__file__).resolve().parent.parent
    tasks = root / "benchmarks" / "tasks"
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    task_text(tasks / "L3_mini_v3.yaml", out / "task_text_L3.tex")
    task_diff(tasks / "L2_mini_v3.yaml", tasks / "L3_mini_v3.yaml",
              out / "task_diff.tex")
    solution_shape(root / "experiments" / args.tag, out / "solution_shape.tex")
    glossary_tex(root / "experiments" / args.tag, out / "glossary.tex")
    print(f"Wrote 4 table fragments to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
